#ifndef CORE_OPERATOR_H
#define CORE_OPERATOR_H

enum CalculateOperator {
    CALCULATE_OPERATOR_ADD_WRAP_AROUND,
    CALCULATE_OPERATOR_SUB_WRAP_AROUND,
    CALCULATE_OPERATOR_MULTIPLY_WRAP_AROUND,
    CALCULATE_OPERATOR_DIV_WRAP_AROUND,
    CALCULATE_OPERATOR_MOD_WRAP_AROUND,
};

enum CompareOperator {
    COMPARE_OPERATOR_EQUAL,
    COMPARE_OPERATOR_NOT_EQUAL,
    COMPARE_OPERATOR_GREATER_THAN,
    COMPARE_OPERATOR_GREATER_THAN_EQUAL,
    COMPARE_OPERATOR_LESS_THAN,
    COMPARE_OPERATOR_LESS_THAN_EQUAL
};

#endif //CORE_OPERATOR_H
