#ifndef CORE_OPERATOR_H
#define CORE_OPERATOR_H

enum CompareOperator {
    COMPARE_OPERATOR_EQUAL,
    COMPARE_OPERATOR_NOT_EQUAL,
    COMPARE_OPERATOR_GREATER_THAN,
    COMPARE_OPERATOR_GREATER_THAN_EQUAL,
    COMPARE_OPERATOR_LESS_THAN,
    COMPARE_OPERATOR_LESS_THAN_EQUAL
};

#endif //CORE_OPERATOR_H
