#ifndef CORE_VAL_KIND_H
#define CORE_VAL_KIND_H

enum val_kind {
  VAL_KIND_BOOL,
  VAL_KIND_FLD,
  VAL_KIND_FN,
  VAL_KIND_F4,
  VAL_KIND_F8,
  VAL_KIND_I1,
  VAL_KIND_I2,
  VAL_KIND_I4,
  VAL_KIND_I8,
  VAL_KIND_I16,
  VAL_KIND_U1,
  VAL_KIND_U2,
  VAL_KIND_U4,
  VAL_KIND_U8,
  VAL_KIND_U16,
  VAL_KIND_LST,
  VAL_KIND_NUM,
  VAL_KIND_OBJ,
  VAL_KIND_PROP,
  VAL_KIND_REF,
  VAL_KIND_STR,
  VAL_KIND_STR_VIEW,
  VAL_KIND_UNIT
};

#endif //CORE_VAL_KIND_H
