#ifndef CORE_VAL_KIND_H
#define CORE_VAL_KIND_H

enum val_kind {
  VAL_KIND_BOOL,
  VAL_KIND_CLSR,
  VAL_KIND_FLD,
  VAL_KIND_FN,
  VAL_KIND_LST,
  VAL_KIND_MOD,
  VAL_KIND_NIL,
  VAL_KIND_NUM,
  VAL_KIND_OBJ,
  VAL_KIND_PROP,
  VAL_KIND_REF,
  VAL_KIND_STR,
  VAL_KIND_STR_VIEW,
  VAL_KIND_UNIT
};

#endif //CORE_VAL_KIND_H
